name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    # TODO: Fix this
    #- name: Link SwiftLint or install it
     # run: brew link --overwrite swiftlint || brew install swiftlint || brew link --overwrite swiftlint
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
